# Generated by Django 3.1.3 on 2020-12-03 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='uname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tuser'),
        ),
    ]
