# Generated by Django 3.1.3 on 2020-12-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuser',
            old_name='username',
            new_name='uname',
        ),
    ]
